### ISSUE TITLE
Light sensor calibration function does not work

### ISSUE THREAD

**Issue by tcorbly** [kipr/libwallaby#120]
In botball_c.cpp the wait_for_light function does not properly take light sensor readings.

**Comment by Zacharyprime** [comment]
I fixed the problem in this commit:
https://github.com/kipr/libwallaby/commit/ae3851bb329a5c532d031e64948021c6bd42abad

It got unfixed by this commit:
https://github.com/kipr/libwallaby/commit/a761b354c6b0b670736a7f0b4cee05c27a9ac304


So then I fixed it again with this commit:
https://github.com/kipr/libwallaby/commit/6ea61d5c187148a3eb6a59197c87a785618b1249

The graphics library does not however seem to be what crashed the old one, so we will eventually re-add the fancy graphics box instead of my ASCII lightbulb. Maybe we can make it even better the second time.
