### ISSUE TITLE
Accessing the camera object

### ISSUE THREAD

**Issue by ryanvade** [kipr/libwallaby#82]
I'm trying to obtain the camera object.  Would I need to include camera_c_p.cpp and then use DeviceSingleton::instance() ?

Once I have the object,  how do I grab a frame?

**Comment by jsoutherland** [comment]
@ryanvade yep the ``Device:Singleton::instance()`` is what you want.  How you access it and use it depends on if you are adding your code into our codebase/build or using our library to test your code.

If you are adding your code into libwallaby/src (and updating CMakeLists.txt to build it as well), you can get access to include ``camera_c_p.hpp`` and then follow the examples  in https://github.com/kipr/libwallaby/blob/master/src/camera_c.cpp  since it is using the same interface at that point.   You will see how  to open and close the camera, as well as how to grab a frame: https://github.com/kipr/libwallaby/blob/master/src/camera_c.cpp#L301-L304

It might be better to link against libwallaby and include/use either of the public interfaces:  
https://github.com/kipr/libwallaby/blob/master/include/wallaby/camera.h
or https://github.com/kipr/libwallaby/blob/master/include/wallaby/camera.hpp


If you go with the C++ header (camera.hpp) it may be useful to look at the botui camera widget which does similar work with the camera:
Opening: https://github.com/kipr/botui/blob/master/src/CameraWidget.cpp#L14
Updating: https://github.com/kipr/botui/blob/master/src/CameraWidget.cpp#L78
Using the image: https://github.com/kipr/botui/blob/master/src/CameraWidget.cpp#L85
Closing: https://github.com/kipr/botui/blob/master/src/CameraWidget.cpp#L23

One last thing... if you are using the black logitech camera you will have better luck with the equivalent of:
https://github.com/kipr/libwallaby/blob/master/src/camera_c.cpp#L24-L27  which uses OpenCV for jpeg decoding and is faster.
With  Aruco codes it might be useful to pass ``MED_RES`` instead of ``LOW_RES`` to be able to distinguish markers from further away.   The Wallabies can't handle HIGH_RES.
